version: '3.8'
services:
  zircon_proto:
    extends:
      file: config.yml
      service: zircon_proto
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - "8088:8088"

 
